CocInstall coc-css
CocInstall coc-diagnostic
CocInstall coc-docker
CocInstall coc-emoji
CocInstall coc-eslint
CocInstall coc-html
CocInstall coc-json
CocInstall coc-lua
CocInstall coc-prettier
CocInstall coc-python
CocInstall coc-rls
CocInstall coc-sh
CocInstall coc-svg
CocInstall coc-tsserver
CocInstall coc-vimlsp
CocInstall coc-vimtex
CocInstall coc-wxml
CocInstall coc-yaml
CocInstall coc-yank
CocInstall coc-ultisnips
CocInstall coc-go
CocInstall coc-github
CocInstall coc-lsp-wl
