CocInstall coc-clangd
CocInstall coc-cmake
CocInstall coc-css
CocInstall coc-diagnostic
CocInstall coc-docker
CocInstall coc-emoji
CocInstall coc-eslint
CocInstall coc-go
CocInstall coc-html
CocInstall coc-json
CocInstall coc-lsp-wl
CocInstall coc-prettier
CocInstall coc-python
CocInstall coc-rls
CocInstall coc-sh
CocInstall coc-snippets
CocInstall coc-svg
CocInstall coc-texlab
CocInstall coc-tsserver
CocInstall coc-vimlsp
CocInstall coc-wxml
CocInstall coc-yaml
CocInstall coc-yank
