CocInstall coc-css
CocInstall coc-diagnostica
CocInstall coc-docker
CocInstall coc-emojia
CocInstall coc-eslint
CocInstall coc-htmla
CocInstall coc-jsona
CocInstall coc-luaa
CocInstall coc-prettier
CocInstall coc-python
CocInstall coc-rlsa
CocInstall coc-sha
CocInstall coc-svga
CocInstall coc-tsserver
CocInstall coc-vimlsp
CocInstall coc-vimtexa
CocInstall coc-wxmla
CocInstall coc-yamla
CocInstall coc-yanka
CocInstall coc-ultisnips
